export default [
  'Acai',
  'American',
  'Asian',
  'Australian',
  'BBQ',
  'Bao',
  'Beef',
  'Biryani',
  'Breakfast',
  'Brunch',
  'Bubble tea',
  'Burgers',
  'Burritos',
  'Café',
  'Cheap Eats',
  'Chicken',
  'Chinese',
  'Coffee',
  'Comfort food',
  'Congee',
  'Curry',
  'Curry Goat',
  'Dessert',
  'Desserts and sweet dishes',
  'Dim Sum',
  'Duck',
  'Dumplings',
  'European',
  'Family favourites',
  'Fast Food',
  'Fastest delivery',
  'Featured',
  'Fish',
  'Fish and chips',
  'Fried chicken',
  'Gelato',
  'Great for lunch',
  'Greek',
  'Grill',
  'Grocery',
  'Healthy',
  'Hispanic',
  'Ice cream',
  'Indian',
  'Italian',
  'Japanese',
  'Juices',
  'Kids Menu',
  'Late Night Delivery',
  'Local gems',
  'Malaysian',
  'Meatballs',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'Milkshakes',
  'New on Deliveroo',
  'Noodles',
  'Office Catering',
  'Only on Deliveroo',
  'Order again',
  'Pasta',
  'Perfect for sharing',
  'Peri peri',
  'Pizza',
  'Poke',
  'Ribs',
  'Rice',
  'Salads',
  'Sandwiches',
  'Schnitzel',
  'Seafood',
  'Smoothie',
  'Soup',
  'South Indian',
  'Souvlaki',
  'Spicy',
  'Steak',
  'Stir fry',
  'Street food',
  'Sushi',
  'Sweet treats',
  'Taiwanese',
  'Tea',
  'Thai',
  'Top rated',
  'Vietnamese',
  'Wings',
  'Wraps',
];
